//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chatlogs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub channel_id: i32,
    pub timestamp: DateTime,
    pub username: String,
    pub message: String,
    pub external_user_account_id: Option<i32>,
    pub import_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "(Column::ChannelId, Column::ChannelId)",
        to = "(super::channels::Column::Id, super::channels::Column::Id)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Channels,
    #[sea_orm(
        belongs_to = "super::chatlog_imports::Entity",
        from = "(Column::ImportId, Column::ImportId)",
        to = "(super::chatlog_imports::Column::Id, super::chatlog_imports::Column::Id)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChatlogImports,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::chatlog_imports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatlogImports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
