//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "content_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub content_id: i32,
    pub watched: bool,
    pub watched_at: Option<DateTime>,
    pub broadcaster_id: i32,
    pub skipped: bool,
    #[sea_orm(column_type = "Double")]
    pub score: f64,
    pub content_timestamp: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::broadcaster::Entity",
        from = "Column::BroadcasterId",
        to = "super::broadcaster::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Broadcaster,
    #[sea_orm(
        belongs_to = "super::content::Entity",
        from = "Column::ContentId",
        to = "super::content::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Content,
    #[sea_orm(has_many = "super::content_queue_submissions::Entity")]
    ContentQueueSubmissions,
}

impl Related<super::broadcaster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Broadcaster.def()
    }
}

impl Related<super::content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Content.def()
    }
}

impl Related<super::content_queue_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentQueueSubmissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
