//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "segments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub start: i32,
    pub end: i32,
    pub transcription_id: i32,
    pub previous_segment_id: Option<i32>,
    pub next_segment_id: Option<i32>,
    #[sea_orm(column_type = "custom(\"tsvector\")")]
    pub text_tsv: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::transcriptions::Entity",
        from = "Column::TranscriptionId",
        to = "super::transcriptions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transcriptions,
}

impl Related<super::transcriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transcriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
