//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_weights")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    #[sea_orm(column_type = "Double")]
    pub weight: f64,
    pub broadcaster_id: i32,
    pub banned: bool,
    pub banned_at: Option<DateTime>,
    pub unban_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::broadcaster::Entity",
        from = "Column::BroadcasterId",
        to = "super::broadcaster::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Broadcaster,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::broadcaster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Broadcaster.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
