[package]
name = "yappr-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Document",
  "Element",
  "Node",
  "HtmlElement",
  "HtmlInputElement", 
  "HtmlTextAreaElement",
  "HtmlCanvasElement",
  "HtmlSelectElement",
  "HtmlAnchorElement",
  "CanvasRenderingContext2d",
  "NodeList",
  "Window",
  "Storage",
  "CssStyleDeclaration",
  "HtmlCollection",
  "MouseEvent",
  "EventTarget",
  "Event",
  "PointerEvent",
  "DomRect",
  "Location",
]

[profile.release]
lto = true
opt-level = "s"