"""user comments to submissions

Revision ID: 038f881fd4f3
Revises: de3b22107493
Create Date: 2025-05-31 02:04:10.996638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '038f881fd4f3'
down_revision: Union[str, None] = 'de3b22107493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_queue_submissions', sa.Column('user_comment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_queue_submissions', 'user_comment')
    # ### end Alembic commands ###
