"""add content rating

Revision ID: 0a63df7fd2db
Revises: f24ae7bf1ed8
Create Date: 2025-07-07 07:14:39.835048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0a63df7fd2db'
down_revision: Union[str, None] = 'f24ae7bf1ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_queue', sa.Column('score', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_queue', 'score')
    # ### end Alembic commands ###
