"""stricter types

Revision ID: 0fb4193593f2
Revises: 7b4c3f928560
Create Date: 2025-07-29 15:33:41.252084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0fb4193593f2'
down_revision: Union[str, None] = '7b4c3f928560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('platform_name', sa.String(length=250), nullable=True))
    op.execute("UPDATE channels set platform_name = CASE WHEN platform_id = 1 THEN 'youtube' WHEN platform_id = 2 THEN 'twitch' ELSE 'unknown' END")
    op.alter_column('channels', 'platform_name', nullable=False)
    op.alter_column('channels', 'platform_channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('channels_platform_id_fkey'), 'channels', type_='foreignkey')
    op.drop_column('channels', 'platform_id')
    op.alter_column('users', 'external_account_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'external_account_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('channels', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('channels_platform_id_fkey'), 'channels', 'platforms', ['platform_id'], ['id'])
    op.alter_column('channels', 'platform_channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('channels', 'platform_name')
    # ### end Alembic commands ###
