"""discord thread settings

Revision ID: 106db04acf33
Revises: bfb1ccefa93a
Create Date: 2025-06-07 23:22:14.343914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '106db04acf33'
down_revision: Union[str, None] = 'bfb1ccefa93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcaster_settings', sa.Column('linked_discord_threads_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcaster_settings', 'linked_discord_threads_enabled')
    # ### end Alembic commands ###
