"""convert segment content to text

Revision ID: 13c1bfc99f1a
Revises: 222523337603
Create Date: 2025-04-20 13:00:04.091310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = "13c1bfc99f1a"
down_revision: Union[str, None] = "222523337603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "segments",
        "text",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.add_column(
        "segments",
        sa.Column(
            "text_tsv",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            sa.Computed("to_tsvector('simple', \"text\")", persisted=True),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segments", "text_tsv")
    op.alter_column(
        "segments",
        "text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
