"""external user settings

Revision ID: 1d74721bf16b
Revises: 9cc75a276a14
Create Date: 2025-06-22 22:11:46.292335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1d74721bf16b'
down_revision: Union[str, None] = '9cc75a276a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_user_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('broadcaster_id', sa.Integer(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('unban_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcaster_id'], ['broadcaster.id'], ),
    sa.ForeignKeyConstraint(['external_user_id'], ['external_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_user_weights')
    # ### end Alembic commands ###
