"""add previous-next segments

Revision ID: 222523337603
Revises: 70de17b93b2e
Create Date: 2025-04-20 00:46:31.622133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = "222523337603"
down_revision: Union[str, None] = "70de17b93b2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segments", sa.Column("previous_segment_id", sa.Integer(), nullable=True)
    )
    op.add_column("segments", sa.Column("next_segment_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segments", "previous_segment_id")
    op.drop_column("segments", "next_segment_id")
    # ### end Alembic commands ###
