"""$@

Revision ID: 24e5a3473bf0
Revises: 9b7915afef2c
Create Date: 2025-08-30 08:52:25.760874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '24e5a3473bf0'
down_revision: Union[str, None] = '9b7915afef2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new 'Live' value to videotype enum
    op.execute("ALTER TYPE videotype ADD VALUE 'Live'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support removing enum values directly
    # Manual intervention would be required to remove the 'Live' value
    pass
    # ### end Alembic commands ###
