"""add-audio-file

Revision ID: 27ea41469d7f
Revises: 63e0e0cc0442
Create Date: 2025-04-06 01:21:34.785441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '27ea41469d7f'
down_revision: Union[str, None] = '63e0e0cc0442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('audio', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'audio')
    # ### end Alembic commands ###
