"""add upload date to videos

Revision ID: 28f74a2de022
Revises: b9b02a5999ce
Create Date: 2025-04-08 00:36:52.697737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '28f74a2de022'
down_revision: Union[str, None] = 'b9b02a5999ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('uploaded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'uploaded')
    # ### end Alembic commands ###
