"""$@

Revision ID: 2bbe1f8736f5
Revises: 40bdde12a9e8
Create Date: 2025-09-14 18:07:27.991244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2bbe1f8736f5'
down_revision: Union[str, None] = '40bdde12a9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation_actions', 'issued_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation_actions', 'issued_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
