"""oauth2

Revision ID: 2ea5da67d56d
Revises: 8197cf48587e
Create Date: 2025-04-14 17:48:09.586350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '2ea5da67d56d'
down_revision: Union[str, None] = '8197cf48587e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flask_dance_oauth', sa.Column('provider_user_id', sa.String(length=256), nullable=False))
    op.drop_index('ix_flask_dance_oauth_user_id', table_name='flask_dance_oauth')
    op.create_unique_constraint(None, 'flask_dance_oauth', ['provider_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flask_dance_oauth', type_='unique')
    op.create_index('ix_flask_dance_oauth_user_id', 'flask_dance_oauth', ['user_id'], unique=False)
    op.drop_column('flask_dance_oauth', 'provider_user_id')
    # ### end Alembic commands ###
