"""$@

Revision ID: 40bdde12a9e8
Revises: 2a0d6e63242f
Create Date: 2025-09-08 20:45:01.230835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '40bdde12a9e8'
down_revision: Union[str, None] = '2a0d6e63242f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chatlogs_channel_timestamp', 'chatlogs', ['channel_id', 'timestamp'], unique=False)
    op.add_column('content_queue', sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_queue', 'disabled')
    op.drop_index('ix_chatlogs_channel_timestamp', table_name='chatlogs')
    # ### end Alembic commands ###
