"""add moderator role

Revision ID: 41d6cc75e8a5
Revises: fe504c0117ea
Create Date: 2025-04-27 23:00:54.349648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "41d6cc75e8a5"
down_revision: Union[str, None] = "fe504c0117ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permissiontype ADD VALUE 'Moderator';")
    op.alter_column(
        "permissions",
        "permission_type",
        existing_type=sa.Enum("Admin", "Reader", "Moderator", name="permissiontype"),
        nullable=False,
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permissiontype REMOVE VALUE 'Moderator';")
    op.alter_column(
        "permissions",
        "permission_type",
        existing_type=sa.Enum("Admin", "Reader", name="permissiontype"),
        nullable=False,
    )
    pass
    # ### end Alembic commands ###
