"""add platform channel id for internal platform ref

Revision ID: 50da5760d226
Revises: 6fdd09df45ff
Create Date: 2025-04-13 15:25:26.904312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '50da5760d226'
down_revision: Union[str, None] = '6fdd09df45ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('platform_channel_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'channels', ['platform_channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'platform_channel_id')
    # ### end Alembic commands ###
