"""add source video and campaign ref

Revision ID: 56e843841da9
Revises: 41d6cc75e8a5
Create Date: 2025-05-05 19:37:41.728001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "56e843841da9"
down_revision: Union[str, None] = "41d6cc75e8a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("source_channel_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_channels_source_channel_id"),
        "channels",
        ["source_channel_id"],
        unique=False,
    )
    op.create_foreign_key(None, "channels", "channels", ["source_channel_id"], ["id"])
    op.add_column("video", sa.Column("source_video_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_video_source_video_id"), "video", ["source_video_id"], unique=False
    )
    op.create_foreign_key(None, "video", "video", ["source_video_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("video_source_video_id_fkey", "video", type_="foreignkey")
    op.drop_index(op.f("ix_video_source_video_id"), table_name="video")
    op.drop_column("video", "source_video_id")
    op.drop_constraint("channels_pkey", "channels", type_="foreignkey")
    op.drop_index(op.f("ix_channels_source_channel_id"), table_name="channels")
    op.drop_column("channels", "source_channel_id")
    # ### end Alembic commands ###
