"""add platform branding color

Revision ID: 570cd43305f5
Revises: 13c1bfc99f1a
Create Date: 2025-04-24 21:23:49.296418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '570cd43305f5'
down_revision: Union[str, None] = '13c1bfc99f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('color', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_segments_text_tsv'), 'segments', ['text_tsv'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_text_tsv'), table_name='segments')
    op.drop_column('platforms', 'color')
    # ### end Alembic commands ###
