"""thumbnail-optional

Revision ID: 63e0e0cc0442
Revises: f20e2a0cbe03
Create Date: 2025-04-05 14:39:38.206195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '63e0e0cc0442'
down_revision: Union[str, None] = 'f20e2a0cbe03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail')
    # ### end Alembic commands ###
