"""contentqueue add missing submission ref

Revision ID: 6d115ce78e09
Revises: f4a3eeb06227
Create Date: 2025-05-29 14:12:25.801024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6d115ce78e09'
down_revision: Union[str, None] = 'f4a3eeb06227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_queue_submissions', sa.Column('content_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content_queue_submissions', 'content', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_queue_submissions_content_id_fkey', 'content_queue_submissions', type_='foreignkey')
    op.drop_column('content_queue_submissions', 'content_id')
    # ### end Alembic commands ###
