"""add missing user link in permissions3

Revision ID: 6fdd09df45ff
Revises: 6779d6724136
Create Date: 2025-04-09 16:45:12.669667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fdd09df45ff'
down_revision: Union[str, None] = '6779d6724136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('permission_type', sa.Enum('Admin', 'Reader', name='permissiontype'), nullable=False))
    op.drop_column('permissions', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('account_type', postgresql.ENUM('Admin', 'Reader', name='permissiontype'), autoincrement=False, nullable=False))
    op.drop_column('permissions', 'permission_type')
    # ### end Alembic commands ###
