"""add processed tag on transcriptions

Revision ID: 70de17b93b2e
Revises: 663ea34e3293
Create Date: 2025-04-16 15:23:39.599134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = "70de17b93b2e"
down_revision: Union[str, None] = "663ea34e3293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcriptions", sa.Column("processed", sa.Boolean(), nullable=True))
    op.execute("UPDATE transcriptions set processed = False")
    op.alter_column(
        "transcriptions", "processed", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcriptions", "processed")
    # ### end Alembic commands ###
