"""make segment endtime required

Revision ID: 767128e66291
Revises: 27ea41469d7f
Create Date: 2025-04-06 14:58:28.746436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '767128e66291'
down_revision: Union[str, None] = '27ea41469d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 'end',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 'end',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
