"""add timestamp to content submissions

Revision ID: 7b4c3f928560
Revises: 5da1eee4d713
Create Date: 2025-07-21 21:53:02.280364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7b4c3f928560'
down_revision: Union[str, None] = '5da1eee4d713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_queue', sa.Column('content_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_queue', 'content_timestamp')
    # ### end Alembic commands ###
