"""$@

Revision ID: 815751c768a9
Revises: 2116bd55af44
Create Date: 2025-08-31 20:36:29.607572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '815751c768a9'
down_revision: Union[str, None] = '2116bd55af44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcaster', sa.Column('profile_image_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcaster', 'profile_image_url')
    # ### end Alembic commands ###
