"""user broadcaster mapping

Revision ID: 8b53509b9088
Revises: 97ae30d063ed
Create Date: 2025-04-27 11:16:56.195206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '8b53509b9088'
down_revision: Union[str, None] = '97ae30d063ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('broadcaster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'broadcaster', ['broadcaster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'broadcaster_id')
    # ### end Alembic commands ###
