"""$@

Revision ID: 919f4fbd346c
Revises: 2bbe1f8736f5
Create Date: 2025-09-14 21:46:42.083209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '919f4fbd346c'
down_revision: Union[str, None] = '2bbe1f8736f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_queue_submissions', sa.Column('submission_source_ref', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_queue_submissions', 'submission_source_ref')
    # ### end Alembic commands ###
