"""content add details

Revision ID: 928e5eff03f8
Revises: 6d115ce78e09
Create Date: 2025-05-29 17:33:24.532939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '928e5eff03f8'
down_revision: Union[str, None] = '6d115ce78e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('title', sa.String(length=256)))
    op.execute("UPDATE content set title = 'No title'")
    op.alter_column('content', 'title', nullable=False)

    op.add_column('content', sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
    op.add_column('content', sa.Column('stripped_url', sa.String(length=1000)))
    op.execute("UPDATE content set stripped_url = url")
    op.alter_column('content', 'stripped_url', nullable=False)
    op.add_column('content', sa.Column('channel_name', sa.String(length=500)))
    op.execute("UPDATE content set channel_name = 'No channel name'")
    op.alter_column('content', 'channel_name', nullable=False)
    op.add_column('content', sa.Column('author', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'author')
    op.drop_column('content', 'channel_name')
    op.drop_column('content', 'thumbnail_url')
    op.drop_column('content', 'title')
    op.drop_column('content', 'stripped_url')
    # ### end Alembic commands ###
