"""$@

Revision ID: 967427e6d874
Revises: b28d3c8f27e0
Create Date: 2025-08-25 20:23:37.486220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '967427e6d874'
down_revision: Union[str, None] = 'b28d3c8f27e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamp_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=False),
    sa.Column('target_video_id', sa.Integer(), nullable=False),
    sa.Column('source_start_time', sa.Float(), nullable=False),
    sa.Column('source_end_time', sa.Float(), nullable=False),
    sa.Column('target_start_time', sa.Float(), nullable=False),
    sa.Column('target_end_time', sa.Float(), nullable=False),
    sa.Column('time_offset', sa.Float(), nullable=False),
    sa.Column('cuts_data', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['target_video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_mapping_source_video_id'), 'timestamp_mapping', ['source_video_id'], unique=False)
    op.create_index(op.f('ix_timestamp_mapping_target_video_id'), 'timestamp_mapping', ['target_video_id'], unique=False)
    op.drop_index(op.f('ix_channels_source_channel_id'), table_name='channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_channels_source_channel_id'), 'channels', ['source_channel_id'], unique=False)
    op.drop_index(op.f('ix_timestamp_mapping_target_video_id'), table_name='timestamp_mapping')
    op.drop_index(op.f('ix_timestamp_mapping_source_video_id'), table_name='timestamp_mapping')
    op.drop_table('timestamp_mapping')
    # ### end Alembic commands ###
