"""user ban

Revision ID: 97ae30d063ed
Revises: 570cd43305f5
Create Date: 2025-04-24 23:36:09.466235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "97ae30d063ed"
down_revision: Union[str, None] = "570cd43305f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("banned_reason", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("banned", sa.Boolean(), nullable=True))
    op.execute("UPDATE users set banned = False")
    op.alter_column("users", "banned", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "banned_reason")
    op.drop_column("users", "banned")
    # ### end Alembic commands ###
