"""$@

Revision ID: 99f2bb3528a7
Revises: 24e5a3473bf0
Create Date: 2025-08-31 11:46:20.716523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '99f2bb3528a7'
down_revision: Union[str, None] = '24e5a3473bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing events since we're changing the schema significantly
    op.execute("DELETE FROM channel_events")
    
    # Create the enum type first
    channel_event_type = sa.Enum('Live', 'Offline', 'Raid', 'Cheer', 'Subscription', 'Gift', 'Follow', name='channeleventtype')
    channel_event_type.create(op.get_bind())
    
    op.add_column('channel_events', sa.Column('event_type', channel_event_type, nullable=False))
    op.add_column('channel_events', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('channel_events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('channel_events', sa.Column('import_id', sa.Integer(), nullable=True))
    op.alter_column('channel_events', 'raw_message',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_foreign_key(None, 'channel_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'channel_events', 'chatlog_imports', ['import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_events', type_='foreignkey')
    op.drop_constraint(None, 'channel_events', type_='foreignkey')
    op.alter_column('channel_events', 'raw_message',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('channel_events', 'import_id')
    op.drop_column('channel_events', 'user_id')
    op.drop_column('channel_events', 'username')
    op.drop_column('channel_events', 'event_type')
    
    # Drop the enum type
    sa.Enum(name='channeleventtype').drop(op.get_bind())
    # ### end Alembic commands ###
