"""make last_login optional

Revision ID: 9b7915afef2c
Revises: e48ae5054d4a
Create Date: 2025-08-28 23:02:14.615962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b7915afef2c'
down_revision: Union[str, None] = 'e48ae5054d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'first_login')
    
    # Set last_login to NULL where avatar_url is NULL
    op.execute("""
        UPDATE users 
        SET last_login = NULL 
        WHERE avatar_url IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
