"""$@

Revision ID: 9bcb1b066d74
Revises: 815751c768a9
Create Date: 2025-09-01 00:41:06.212558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9bcb1b066d74'
down_revision: Union[str, None] = '815751c768a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_moderators')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_moderators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('channel_moderators_channel_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('channel_moderators_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_moderators_pkey'))
    )
    # ### end Alembic commands ###
