"""add title_date_parsing_enabled to channel_settings

Revision ID: b28d3c8f27e0
Revises: e9245b999c9f
Create Date: 2025-08-24 23:24:20.976385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b28d3c8f27e0'
down_revision: Union[str, None] = 'e9245b999c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('estimated_upload_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'estimated_upload_time')
    # ### end Alembic commands ###
