"""chatlog remove constraint and make int

Revision ID: bc541bcf1b53
Revises: c8771a735d9f
Create Date: 2025-05-29 13:22:53.427351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'bc541bcf1b53'
down_revision: Union[str, None] = 'c8771a735d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatlogs_external_user_account_id_fkey', 'chatlogs', type_='foreignkey')
    op.alter_column('chatlogs', 'external_user_account_id',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Integer(),
               postgresql_using="external_user_account_id::integer",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chatlogs_external_user_account_id_fkey', 'chatlogs', 'external_users', ['external_user_account_id'], ['external_account_id'])
    op.alter_column('chatlogs', 'external_user_account_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
