"""$@

Revision ID: ccf252ee5d14
Revises: 967427e6d874
Create Date: 2025-08-25 20:45:59.619826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ccf252ee5d14'
down_revision: Union[str, None] = '967427e6d874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_source_video_id'), table_name='video')
    op.drop_constraint(op.f('video_source_video_id_fkey'), 'video', type_='foreignkey')
    op.drop_column('video', 'source_video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('source_video_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('video_source_video_id_fkey'), 'video', 'video', ['source_video_id'], ['id'])
    op.create_index(op.f('ix_video_source_video_id'), 'video', ['source_video_id'], unique=False)
    # ### end Alembic commands ###
