"""fix segments text_tsv index to use gin instead of btree

Revision ID: dac5aa82b7dd
Revises: ed5342db4a63
Create Date: 2025-08-06 15:51:10.314686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'dac5aa82b7dd'
down_revision: Union[str, None] = 'ed5342db4a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_text_tsv'), table_name='segments')
    op.create_index('ix_segments_text_tsv_gin', 'segments', ['text_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segments_text_tsv_gin', table_name='segments', postgresql_using='gin')
    op.create_index(op.f('ix_segments_text_tsv'), 'segments', ['text_tsv'], unique=False)
    # ### end Alembic commands ###
