"""twitch oauth

Revision ID: db91552b49ed
Revises: 8ff428eff057
Create Date: 2025-05-26 18:58:48.684901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'db91552b49ed'
down_revision: Union[str, None] = '8ff428eff057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE accountsource ADD VALUE IF NOT EXISTS 'Twitch'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No migration back, only gass no breaks
    pass
    # ### end Alembic commands ###
