"""init

Revision ID: dbfd73de2e1f
Revises: 
Create Date: 2025-04-04 18:33:38.240561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfd73de2e1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_segments_transcription_id'), 'segments', ['transcription_id'], unique=False)
    op.drop_constraint('transcriptions_video_id_key', 'transcriptions', type_='unique')
    op.create_index(op.f('ix_transcriptions_video_id'), 'transcriptions', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_channel_id'), 'video', ['channel_id'], unique=False)
    op.drop_index('wordmap_word', table_name='wordmaps', postgresql_with={'deduplicate_items': 'true'})
    op.create_index(op.f('ix_wordmaps_transcription_id'), 'wordmaps', ['transcription_id'], unique=False)
    op.create_index(op.f('ix_wordmaps_word'), 'wordmaps', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordmaps_word'), table_name='wordmaps')
    op.drop_index(op.f('ix_wordmaps_transcription_id'), table_name='wordmaps')
    op.create_index('wordmap_word', 'wordmaps', ['word', 'transcription_id'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    op.drop_index(op.f('ix_video_channel_id'), table_name='video')
    op.drop_index(op.f('ix_transcriptions_video_id'), table_name='transcriptions')
    op.create_unique_constraint('transcriptions_video_id_key', 'transcriptions', ['video_id'])
    op.drop_index(op.f('ix_segments_transcription_id'), table_name='segments')
    # ### end Alembic commands ###
