"""hide broadcasters

Revision ID: df1d0da8b1e5
Revises: 56e843841da9
Create Date: 2025-05-08 18:36:16.223580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "df1d0da8b1e5"
down_revision: Union[str, None] = "56e843841da9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "broadcaster",
        sa.Column("hidden", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE broadcaster SET hidden=False")
    op.alter_column("broadcaster", "hidden", nullable=False, default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcaster", "hidden")
    # ### end Alembic commands ###
