"""remove broadcaster_id column from users table

Revision ID: e48ae5054d4a
Revises: e23a203a7138
Create Date: 2025-08-28 22:19:30.135159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e48ae5054d4a'
down_revision: Union[str, None] = 'e23a203a7138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_broadcaster_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'broadcaster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('broadcaster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_broadcaster_id_fkey'), 'users', 'broadcaster', ['broadcaster_id'], ['id'])
    # ### end Alembic commands ###
