"""add userid to chatlog

Revision ID: e48f45e306e4
Revises: f27b17547c9a
Create Date: 2025-05-29 10:39:59.173027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e48f45e306e4'
down_revision: Union[str, None] = 'f27b17547c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatlogs', sa.Column('external_user_account_id', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'chatlogs', 'external_users', ['external_user_account_id'], ['external_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatlogs', type_='foreignkey')
    op.drop_column('chatlogs', 'external_user_account_id')
    # ### end Alembic commands ###
