"""$@

Revision ID: e9245b999c9f
Revises: ad68a1448763
Create Date: 2025-08-24 22:21:46.959636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e9245b999c9f'
down_revision: Union[str, None] = 'ad68a1448763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatlog_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chatlogs', sa.Column('import_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chatlogs', 'chatlog_imports', ['import_id'], ['id'])
    op.drop_column('chatlogs', 'imported')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatlogs', sa.Column('imported', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chatlogs', type_='foreignkey')
    op.drop_column('chatlogs', 'import_id')
    op.drop_table('chatlog_imports')
    # ### end Alembic commands ###
