"""add content queue settings

Revision ID: f24ae7bf1ed8
Revises: e8d73449d782
Create Date: 2025-07-06 20:24:18.839827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f24ae7bf1ed8'
down_revision: Union[str, None] = 'e8d73449d782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_queue_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcaster_id', sa.Integer(), nullable=False),
    sa.Column('prefer_shorter_content', sa.Boolean(), nullable=False),
    sa.Column('view_count_min', sa.Integer(), nullable=False),
    sa.Column('allowed_platforms', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['broadcaster_id'], ['broadcaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_queue_settings')
    # ### end Alembic commands ###
