"""videos active status

Revision ID: fe504c0117ea
Revises: 8b53509b9088
Create Date: 2025-04-27 14:39:50.843391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "fe504c0117ea"
down_revision: Union[str, None] = "8b53509b9088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("active", sa.Boolean(), nullable=True))
    op.execute("UPDATE video set active = True")
    op.alter_column("video", "active", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "active")
    # ### end Alembic commands ###
