//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "accountsource")]
pub enum Accountsource {
    #[sea_orm(string_value = "Discord")]
    Discord,
    #[sea_orm(string_value = "Twitch")]
    Twitch,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channeleventtype")]
pub enum Channeleventtype {
    #[sea_orm(string_value = "Live")]
    Live,
    #[sea_orm(string_value = "Offline")]
    Offline,
    #[sea_orm(string_value = "Raid")]
    Raid,
    #[sea_orm(string_value = "Cheer")]
    Cheer,
    #[sea_orm(string_value = "Subscription")]
    Subscription,
    #[sea_orm(string_value = "Gift")]
    Gift,
    #[sea_orm(string_value = "Follow")]
    Follow,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "contentqueuesubmissionsource"
)]
pub enum Contentqueuesubmissionsource {
    #[sea_orm(string_value = "Discord")]
    Discord,
    #[sea_orm(string_value = "Twitch")]
    Twitch,
    #[sea_orm(string_value = "Web")]
    Web,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "permissiontype")]
pub enum Permissiontype {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Reader")]
    Reader,
    #[sea_orm(string_value = "Moderator")]
    Moderator,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transcriptionsource"
)]
pub enum Transcriptionsource {
    #[sea_orm(string_value = "Unknown")]
    Unknown,
    #[sea_orm(string_value = "YouTube")]
    YouTube,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "videotype")]
pub enum Videotype {
    #[sea_orm(string_value = "Unknown")]
    Unknown,
    #[sea_orm(string_value = "VOD")]
    Vod,
    #[sea_orm(string_value = "Clip")]
    Clip,
    #[sea_orm(string_value = "Edit")]
    Edit,
    #[sea_orm(string_value = "Live")]
    Live,
}
