//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Transcriptionsource;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transcriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub video_id: i32,
    pub language: String,
    pub last_updated: DateTime,
    pub file_extention: String,
    pub file: Json,
    pub source: Transcriptionsource,
    pub processed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::segments::Entity")]
    Segments,
    #[sea_orm(
        belongs_to = "super::video::Entity",
        from = "Column::VideoId",
        to = "super::video::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Video,
}

impl Related<super::segments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Segments.def()
    }
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Video.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
